#!/bin/bash
screen-load &
compton --backend glx --paint-on-overlay --glx-no-stencil --vsync opengl-swc --unredir-if-possible --blur-background&
dnust &
fcitx-autostart &
bash ~/bin/TouchpadInit  &
randr --dpi 120 &
