#!/bin/bash
if notify-send "$(xclip -out -selection primary | trans)"; then
  echo google;
elif notify-send "$(xclip -out -selection primary | trans -e bing )"; then
  echo bing;
else
  notify-send "trans error 1"
fi

