#!/bin/bash

wm=$(wmctrl -m | grep 'Name:')

if [ "$wm" = "Name: bspwm" ]
then
	bspc quit
elif [ "$wm" = "Name: i3" ]
then
  i3-msg exit
elif [ "$wm" = "Name: Openbox" ]
then
  openbox --exit
else
  notify-send "Error logout error"
fi
