#!/bin/bash

wm=$(wmctrl -m | grep 'Name:')

if [ "$wm" = "Name: bspwm" ]
then
	vim ~/dotfile/.config/sxhkd/sxhkdrc
elif [ "$wm" = "Name: i3" ]
then
  vim ~/dotfile/.config/i3/config
else
  notify-send "Error hotkey error"
fi
